apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-api-gateway
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - backend-services.yaml
  - migration-job.yaml
  - gateway-deployment.yaml
  - hpa.yaml
  - ingress.yaml
