apiVersion: v1
kind: Namespace
metadata:
  name: production-api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: api-gateway-platform
    environment: production
